<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..tWJleJ' shared service.

return $this->privates['.service_locator..tWJleJ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['option' => function (): \App\Entity\Optione {
    return ($this->privates['.errored..service_locator..tWJleJ.App\\Entity\\Optione'] ?? $this->load('getOptioneService.php'));
}]);
