<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4Ap8ALH' shared service.

return $this->privates['.service_locator.4Ap8ALH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['optionRepository' => function (): \App\Repository\OptionRepository {
    return ($this->privates['App\\Repository\\OptionRepository'] ?? $this->load('getOptionRepositoryService.php'));
}]);
