<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator..tWJleJ.App\Entity\Optione' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator..tWJleJ": it references class "App\\Entity\\Optione" but no such service exists.');
