<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mXVsHZt' shared service.

return $this->privates['.service_locator.mXVsHZt'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['picture' => function (): \App\Entity\Picture {
    return ($this->privates['.errored..service_locator.mXVsHZt.App\\Entity\\Picture'] ?? $this->load('getPictureService.php'));
}]);
