<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6XKfqcl' shared service.

return $this->privates['.service_locator.6XKfqcl'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['notification' => function (): \App\Notification\ContactNotification {
    return ($this->privates['App\\Notification\\ContactNotification'] ?? $this->load('getContactNotificationService.php'));
}, 'property' => function (): \App\Entity\Property {
    return ($this->privates['.errored..service_locator.6XKfqcl.App\\Entity\\Property'] ?? $this->load('getPropertyService.php'));
}]);
