<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['App\\Controller\\Admin\\AdminOptionController::delete' => function () {
    return ($this->privates['.service_locator..tWJleJ'] ?? $this->load('get_ServiceLocator__TWJleJService.php'));
}, 'App\\Controller\\Admin\\AdminOptionController::edit' => function () {
    return ($this->privates['.service_locator..tWJleJ'] ?? $this->load('get_ServiceLocator__TWJleJService.php'));
}, 'App\\Controller\\Admin\\AdminOptionController::index' => function () {
    return ($this->privates['.service_locator.4Ap8ALH'] ?? $this->load('get_ServiceLocator_4Ap8ALHService.php'));
}, 'App\\Controller\\Admin\\AdminPictureController::delete' => function () {
    return ($this->privates['.service_locator.mXVsHZt'] ?? $this->load('get_ServiceLocator_MXVsHZtService.php'));
}, 'App\\Controller\\Admin\\AdminPropertyController::delete' => function () {
    return ($this->privates['.service_locator.WSPhAF2'] ?? $this->load('get_ServiceLocator_WSPhAF2Service.php'));
}, 'App\\Controller\\Admin\\AdminPropertyController::edit' => function () {
    return ($this->privates['.service_locator.WSPhAF2'] ?? $this->load('get_ServiceLocator_WSPhAF2Service.php'));
}, 'App\\Controller\\HomeController::index' => function () {
    return ($this->privates['.service_locator.7ojp8vZ'] ?? $this->load('get_ServiceLocator_7ojp8vZService.php'));
}, 'App\\Controller\\PropertyController::index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\PropertyController::show' => function () {
    return ($this->privates['.service_locator.6XKfqcl'] ?? $this->load('get_ServiceLocator_6XKfqclService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\Admin\\AdminOptionController:delete' => function () {
    return ($this->privates['.service_locator..tWJleJ'] ?? $this->load('get_ServiceLocator__TWJleJService.php'));
}, 'App\\Controller\\Admin\\AdminOptionController:edit' => function () {
    return ($this->privates['.service_locator..tWJleJ'] ?? $this->load('get_ServiceLocator__TWJleJService.php'));
}, 'App\\Controller\\Admin\\AdminOptionController:index' => function () {
    return ($this->privates['.service_locator.4Ap8ALH'] ?? $this->load('get_ServiceLocator_4Ap8ALHService.php'));
}, 'App\\Controller\\Admin\\AdminPictureController:delete' => function () {
    return ($this->privates['.service_locator.mXVsHZt'] ?? $this->load('get_ServiceLocator_MXVsHZtService.php'));
}, 'App\\Controller\\Admin\\AdminPropertyController:delete' => function () {
    return ($this->privates['.service_locator.WSPhAF2'] ?? $this->load('get_ServiceLocator_WSPhAF2Service.php'));
}, 'App\\Controller\\Admin\\AdminPropertyController:edit' => function () {
    return ($this->privates['.service_locator.WSPhAF2'] ?? $this->load('get_ServiceLocator_WSPhAF2Service.php'));
}, 'App\\Controller\\HomeController:index' => function () {
    return ($this->privates['.service_locator.7ojp8vZ'] ?? $this->load('get_ServiceLocator_7ojp8vZService.php'));
}, 'App\\Controller\\PropertyController:index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\PropertyController:show' => function () {
    return ($this->privates['.service_locator.6XKfqcl'] ?? $this->load('get_ServiceLocator_6XKfqclService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
