<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTq1mvo5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTq1mvo5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTq1mvo5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTq1mvo5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTq1mvo5\srcDevDebugProjectContainer([
    'container.build_hash' => 'Tq1mvo5',
    'container.build_id' => '61701af7',
    'container.build_time' => 1587395974,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTq1mvo5');
