<?php

// This file has been auto-generated by the Symfony Cache Component.

return [

'_default' => array (
  'entrypoints' => 
  array (
    'app' => 
    array (
      'js' => 
      array (
        0 => 'http://localhost:8080/build/runtime.js',
        1 => 'http://localhost:8080/build/vendors~app.js',
        2 => 'http://localhost:8080/build/app.js',
      ),
      'css' => 
      array (
        0 => 'http://localhost:8080/build/app.css',
      ),
    ),
  ),
),

];
