<?php

// This file has been auto-generated by the Symfony Cache Component.

return [

'_default' => array (
  'entrypoints' => 
  array (
    'app' => 
    array (
      'js' => 
      array (
        0 => '/build/runtime.e9dea5e6.js',
        1 => '/build/0.fda6fef0.js',
        2 => '/build/app.64bc9805.js',
      ),
      'css' => 
      array (
        0 => '/build/app.99c21d8d.css',
      ),
    ),
  ),
),

];
